# Generated by Django 6.0.3 on 2026-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeknoProje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('detay', models.TextField(verbose_name='Proje Detayları')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('durum', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
            ],
            options={
                'verbose_name': "Büşra'nın Web Projesi",
                'verbose_name_plural': "Büşra'nın Web Projeleri",
            },
        ),
    ]
