# Generated by Django 6.0.3 on 2026-03-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teknoproje',
            options={},
        ),
        migrations.AddField(
            model_name='teknoproje',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='proje_resimleri/'),
        ),
        migrations.AlterField(
            model_name='teknoproje',
            name='baslik',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teknoproje',
            name='detay',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teknoproje',
            name='durum',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teknoproje',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
