# Generated by Django 6.0.3 on 2026-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0002_alter_teknoproje_options_teknoproje_resim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teknoproje',
            name='durum',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı mı?'),
        ),
        migrations.AlterField(
            model_name='teknoproje',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='projeler/'),
        ),
    ]
